const List<Map<String, dynamic>> land2Data = [
  {
    "title": "Midlands 1",
    "description": null,
    "author": "filorux",
    "projectName": "adventure.filorux.midlands 1",
    "version": "0.0.1",
    "dataCache": {
      "running": null,
      "players": [
        {
          "name": "bot 1",
          "money": 1000.0,
          "position": 0,
          "color": 4283215696,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": false,
              "canTrade": true,
              "idle": false
            },
            "description": "Normal BOT"
          }
        },
        {
          "name": "bot 2",
          "money": 1000.0,
          "position": 0,
          "color": 4294947584,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 0.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 1",
          "price": 60,
          "hyp": 30,
          "housePrice": 50,
          "rent": [2, 10, 30, 90, 160, 250],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 2",
          "price": 90,
          "hyp": 30,
          "housePrice": 50,
          "rent": [4, 20, 60, 180, 320, 450],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 200,
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 1",
          "price": 140,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Elektric Company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 27,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 28,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": -300,
          "level": 0,
          "idIndex": 25,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 1",
          "price": 220,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 2",
          "price": 330,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": 4280923894,
          "tableColor": 4279060385
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 200,
          "level": 0,
          "idIndex": 26,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 29,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 1",
          "price": 300,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 2",
          "price": 300,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1250],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 3",
          "price": 470,
          "hyp": 160,
          "housePrice": 200,
          "rent": [28, 150, 450, 1000, 1200, 1400],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 1",
          "price": 350,
          "hyp": 175,
          "housePrice": 200,
          "rent": [35, 175, 500, 1100, 1300, 1500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 2",
          "price": 600,
          "hyp": 200,
          "housePrice": 200,
          "rent": [50, 200, 600, 1400, 1700, 2000],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 30,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        }
      ],
      "settings": {
        "name": "",
        "remotelyBuild": true,
        "goBonus": 200,
        "maxTurnes": 99999,
        "mustAuction": false,
        "startingMoney": 1500,
        "hackerScreen": false,
        "interest": 5,
        "dtlPrice": 2000,
        "startProperties": 0,
        "transportPassGo": true,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": true,
        "receiveProperties": true
      },
      "extensions": [],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true,
        "finished": false
      },
      "rentPayed": false,
      "findingsIndex": 0,
      "eventIndex": 0,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "preset": "web.77.filorux.mainland 1",
      "currency": "£",
      "placeCurrencyInFront": true
    },
    "infoCards": [],
    "primaryColor": null,
    "accentColor": null,
    "template": "classic"
  },
  {
    "title": "midlands 2",
    "description": null,
    "author": "filorux",
    "projectName": "adventure.filorux.midlands 2",
    "version": "0.0.1",
    "dataCache": {
      "running": null,
      "players": [
        {
          "name": "bot 1",
          "money": 1000.0,
          "position": 0,
          "color": 4293467747,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        },
        {
          "name": "bot 2",
          "money": 1000.0,
          "position": 0,
          "color": 4287349578,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        },
        {
          "name": "bot 3",
          "money": 1000.0,
          "position": 0,
          "color": 4278430196,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 0.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 1",
          "price": 78,
          "hyp": 30,
          "housePrice": 50,
          "rent": [2, 10, 30, 90, 160, 250],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 2",
          "price": 78,
          "hyp": 30,
          "housePrice": 50,
          "rent": [4, 20, 60, 180, 320, 450],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Elektric Company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10, 25],
          "level": 0,
          "idIndex": 44,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 200,
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200, 500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light blue 1",
          "price": 130,
          "hyp": 50,
          "housePrice": 50,
          "rent": [6, 30, 90, 270, 400, 550],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 2",
          "price": 130,
          "hyp": 50,
          "housePrice": 50,
          "rent": [6, 30, 90, 270, 400, 550],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 1",
          "price": 182,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 3",
          "price": 156,
          "hyp": 60,
          "housePrice": 50,
          "rent": [8, 40, 100, 300, 450, 600],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 2",
          "price": 182,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 3",
          "price": 208,
          "hyp": 80,
          "housePrice": 100,
          "rent": [12, 60, 180, 500, 700, 900],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10, 25],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 9,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 2",
          "price": 200,
          "rent": [25, 50, 100, 250, 500],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 1",
          "price": 234,
          "hyp": 90,
          "housePrice": 100,
          "rent": [70, 200, 550, 750, 950, 1200],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 39,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 3",
          "price": 260,
          "hyp": 100,
          "housePrice": 100,
          "rent": [80, 220, 600, 800, 1000, 1300],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 1",
          "price": 286,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 3",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 250, 500],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 2",
          "price": 286,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 3",
          "price": 312,
          "hyp": 120,
          "housePrice": 150,
          "rent": [20, 100, 300, 750, 925, 1100],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 1",
          "price": 338,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 2",
          "price": 338,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 1",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 3",
          "price": 364,
          "hyp": 140,
          "housePrice": 150,
          "rent": [24, 120, 360, 850, 1025, 1200],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 2",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1250],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 3",
          "price": 416,
          "hyp": 160,
          "housePrice": 200,
          "rent": [28, 150, 450, 1000, 1200, 1400],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 4",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200, 500],
          "level": 0,
          "idIndex": 4,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 5",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200, 500],
          "level": 0,
          "idIndex": 44,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278228616,
          "idPrefix": "t",
          "name": "teal 1",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 40,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278228616,
          "idPrefix": "t",
          "name": "teal 2",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 41,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278228616,
          "idPrefix": "t",
          "name": "teal 3",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 42,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Expensive Water Company",
          "price": 400,
          "hyp": 200,
          "rent": [8, 20, 50],
          "level": 0,
          "idIndex": 43,
          "mortaged": true,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 1",
          "price": 455,
          "hyp": 175,
          "housePrice": 200,
          "rent": [35, 175, 500, 1100, 1300, 1500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 150,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 2",
          "price": 520,
          "hyp": 200,
          "housePrice": 200,
          "rent": [50, 200, 600, 1400, 1700, 2000],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        }
      ],
      "settings": {
        "name": "",
        "remotelyBuild": true,
        "goBonus": 400,
        "maxTurnes": 99999,
        "mustAuction": false,
        "startingMoney": 1000,
        "hackerScreen": false,
        "interest": 5,
        "dtlPrice": 3000,
        "startProperties": 2,
        "transportPassGo": true,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": true,
        "receiveProperties": true
      },
      "extensions": ["bank", "stock"],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true,
        "finished": false
      },
      "rentPayed": false,
      "findingsIndex": 0,
      "eventIndex": 0,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "preset": "app.77.filorux.midgard 2",
      "currency": "£",
      "placeCurrencyInFront": true
    },
    "infoCards": [],
    "primaryColor": null,
    "accentColor": null,
    "template": "classic"
  },
  {
    "title": "midlands 3",
    "description": null,
    "author": "filorux",
    "projectName": "adventure.filorux.midlands 3",
    "version": "0.0.1",
    "dataCache": {
      "running": null,
      "players": [
        {
          "name": "bot 1",
          "money": 1000.0,
          "position": 0,
          "color": 4278190080,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        },
        {
          "name": "bot 2",
          "money": 1000.0,
          "position": 0,
          "color": 4287349578,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        },
        {
          "name": "bot 3",
          "money": 1000.0,
          "position": 0,
          "color": 4280391411,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 0.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 1",
          "price": 78,
          "hyp": 30,
          "housePrice": 50,
          "rent": [2, 10, 30, 90, 160, 250],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 2",
          "price": 78,
          "hyp": 30,
          "housePrice": 50,
          "rent": [4, 20, 60, 180, 320, 450],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Elektric Company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10, 25],
          "level": 0,
          "idIndex": 44,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200, 500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light blue 1",
          "price": 130,
          "hyp": 50,
          "housePrice": 50,
          "rent": [6, 30, 90, 270, 400, 550],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 2",
          "price": 130,
          "hyp": 50,
          "housePrice": 50,
          "rent": [6, 30, 90, 270, 400, 550],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 1",
          "price": 182,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 3",
          "price": 156,
          "hyp": 60,
          "housePrice": 50,
          "rent": [8, 40, 100, 300, 450, 600],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 2",
          "price": 182,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 3",
          "price": 208,
          "hyp": 80,
          "housePrice": 100,
          "rent": [12, 60, 180, 500, 700, 900],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 2",
          "price": 200,
          "rent": [25, 50, 100, 250, 500],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 42,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 1",
          "price": 234,
          "hyp": 90,
          "housePrice": 100,
          "rent": [14, 70, 200, 550, 750, 950],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 39,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 2",
          "price": 260,
          "hyp": 100,
          "housePrice": 100,
          "rent": [14, 70, 200, 550, 750, 950],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 3",
          "price": 234,
          "hyp": 90,
          "housePrice": 100,
          "rent": [80, 220, 600, 800, 1000, 1300],
          "level": 0,
          "idIndex": 40,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 1",
          "price": 286,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 3",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 250, 500],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 2",
          "price": 286,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 39,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 3",
          "price": 312,
          "hyp": 120,
          "housePrice": 150,
          "rent": [20, 100, 300, 750, 925, 1100],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 1",
          "price": 338,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 2",
          "price": 338,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 1",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 3",
          "price": 364,
          "hyp": 140,
          "housePrice": 150,
          "rent": [24, 120, 360, 850, 1025, 1200],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 2",
          "price": 390,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1250],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 3",
          "price": 416,
          "hyp": 160,
          "housePrice": 200,
          "rent": [28, 150, 450, 1000, 1200, 1400],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10, 25],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 9,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 4",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200, 500],
          "level": 0,
          "idIndex": 4,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 41,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 1",
          "price": 455,
          "hyp": 175,
          "housePrice": 200,
          "rent": [35, 175, 500, 1100, 1300, 1500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 200,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 2",
          "price": 520,
          "hyp": 200,
          "housePrice": 200,
          "rent": [50, 200, 600, 1400, 1700, 2000],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 3",
          "price": 455,
          "hyp": 175,
          "housePrice": 200,
          "rent": [35, 175, 500, 1100, 1300, 1500],
          "level": 0,
          "idIndex": 43,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 44,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        }
      ],
      "settings": {
        "name": "",
        "remotelyBuild": true,
        "goBonus": 300,
        "maxTurnes": 99999,
        "mustAuction": false,
        "startingMoney": 1000,
        "hackerScreen": false,
        "interest": 0,
        "dtlPrice": 3000,
        "startProperties": 2,
        "transportPassGo": true,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": true,
        "receiveProperties": true
      },
      "extensions": ["bank", "stock", "drainTheLake"],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true,
        "finished": false
      },
      "rentPayed": false,
      "findingsIndex": 0,
      "eventIndex": 0,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "preset": "net.78.filorux.midgard 3",
      "currency": "£",
      "placeCurrencyInFront": true
    },
    "infoCards": [
      {
        "title": "Multiple Prisons",
        "content": "You will go to a random prison.",
        "type": "rule"
      }
    ],
    "primaryColor": null,
    "accentColor": null,
    "template": "app.77.filorux.midgard 2"
  },
  {"check shuffle": null},
  {
    "title": "mainland 5",
    "description": null,
    "author": "filorux",
    "projectName": "io.78.filorux.mainland 5",
    "version": "0.0.1",
    "dataCache": {
      "running": null,
      "players": [
        {
          "name": "bot 1",
          "money": 1000.0,
          "position": 0,
          "color": 4283215696,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        },
        {
          "name": "bot 2",
          "money": 1000.0,
          "position": 0,
          "color": 4294947584,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1000.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {
            "type": "normal",
            "aiSettingsCache": {
              "chances": [1.0, 0.9, 0.0, 0.2, 1.0],
              "dealFactor": 1.0,
              "smart": true,
              "canTrade": true,
              "idle": false
            },
            "description": "Hard BOT"
          }
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 0.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 1",
          "price": 60,
          "hyp": 30,
          "housePrice": 50,
          "rent": [2, 10, 30, 90, 160, 250],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 400, 1000],
          "level": 0,
          "idIndex": 29,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 200,
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 400, 1000],
          "level": 0,
          "idIndex": 25,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 1",
          "price": 140,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Elektric Company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 27,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": -300,
          "level": 0,
          "idIndex": 25,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 400, 1000],
          "level": 0,
          "idIndex": 26,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 2",
          "price": 330,
          "hyp": 110,
          "housePrice": 200,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": 4280923894,
          "tableColor": 4279060385
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 400, 1000],
          "level": 0,
          "idIndex": 27,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 1",
          "price": 300,
          "hyp": 150,
          "housePrice": 300,
          "rent": [
            26,
            130,
            390,
            900,
            1100,
            1275,
            1400,
            1700,
            2200,
            2400,
            3000,
            3100,
            3200,
            3300,
            3500,
            4500
          ],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 400, 1000],
          "level": 0,
          "idIndex": 28,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294924066,
          "idPrefix": "DB",
          "name": "Orange",
          "price": 350,
          "hyp": 175,
          "housePrice": 300,
          "rent": [
            35,
            175,
            500,
            1100,
            1300,
            1600,
            1800,
            2000,
            2200,
            2500,
            2800,
            2900,
            3000,
            3100,
            3300,
            4300
          ],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 30,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4279060385
        }
      ],
      "settings": {
        "name": "",
        "remotelyBuild": true,
        "goBonus": 200,
        "maxTurnes": 99999,
        "mustAuction": false,
        "startingMoney": 1500,
        "hackerScreen": false,
        "interest": 5,
        "dtlPrice": 4000,
        "startProperties": 0,
        "transportPassGo": true,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": true,
        "receiveProperties": true
      },
      "extensions": ["bank", "stock", "drainTheLake"],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true,
        "finished": false
      },
      "rentPayed": false,
      "findingsIndex": 0,
      "eventIndex": 0,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "preset": "io.78.filorux.mainland 5",
      "currency": "£",
      "placeCurrencyInFront": true
    },
    "infoCards": [],
    "primaryColor": null,
    "accentColor": null,
    "template": "web.77.filorux.mainland 1"
  }
];
