const List<Map<String, dynamic>> land3Data = [
  {
    "title": "test",
    "description": null,
    "author": "filorux",
    "projectName": "io.78.filorux.test",
    "version": "0.0.1",
    "dataCache": {
      "running": false,
      "players": [
        {
          "name": "Ricardo",
          "money": 1000.0,
          "position": 0,
          "color": 4278238420,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [],
          "moneyHistory": [],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
        },
        {
          "name": "August",
          "money": 1000.0,
          "position": 0,
          "color": 4284513675,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [],
          "moneyHistory": [],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
        },
        {
          "name": "Daisy",
          "money": 1000.0,
          "position": 0,
          "color": 4284955319,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [],
          "moneyHistory": [],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 0.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "This is the start tile of the game.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Wallworth",
          "price": 350,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "A big city. Known for it's oil lamps.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": -100,
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "You bring in a bounty +£100!",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Delinosa",
          "price": 350,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description":
              "A pretty large city. It had the first railway connection with Berbury.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 2",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Hastter",
          "price": 380,
          "hyp": 140,
          "housePrice": 150,
          "rent": [24, 120, 360, 850, 1025, 1200],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description":
              "The capital of the yellow street. Known for it's banking services.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": 4294922834,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Greenworth",
          "price": 400,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description":
              "A big city with a giant central park. Known for its cotton industry",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 3",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Tulman",
          "price": 400,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1250],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "A grey city known for it's metal industry.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 0,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": 4279060385,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Berbury",
          "price": 450,
          "hyp": 160,
          "housePrice": 200,
          "rent": [28, 150, 450, 1000, 1200, 1400],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description":
              "A pretty large city. It had the first railway connection with Delinosa.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 4",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 4,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 5",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 5,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 0
        },
        {
          "type": "company",
          "color": 4278190080,
          "idPrefix": "C",
          "name": "South coal mine",
          "price": 150,
          "hyp": 75,
          "rent": [5, 10, 15, 30, 50],
          "level": 0,
          "idIndex": 0,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": 4294953512
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "You've been robbed by a bandid.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Dry Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 8, 15, 30, 50],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description":
              "Best water company in the world. You have to do the rent times the dice eyes.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "O",
          "name": "Twin Scar 1",
          "price": 100,
          "hyp": 90,
          "housePrice": 100,
          "rent": [10, 20, 35, 50, 60, 70, 100, 200, 550, 750, 950],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description":
              "Twin scar is a rural outpost. It does have potential given enough funding.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "O",
          "name": "Twin Scar 2",
          "price": 100,
          "hyp": 90,
          "housePrice": 100,
          "rent": [10, 20, 35, 50, 60, 70, 100, 200, 550, 750, 950],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description":
              "Twin scar is a rural town full of coal miners. It does have potential given enough funding.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "color": 4278190080,
          "idPrefix": "C",
          "name": "West coal mine",
          "price": 150,
          "hyp": 75,
          "rent": [5, 10, 15, 30, 50],
          "level": 0,
          "idIndex": 5,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": 4294953512
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 6",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 6,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "company",
          "color": 4278190080,
          "idPrefix": "C",
          "name": "North coal mine",
          "price": 150,
          "hyp": 75,
          "rent": [5, 10, 15, 30, 50],
          "level": 0,
          "idIndex": 6,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": 4294953512
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": 4279060385,
          "tableColor": 4294953512
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Upper Water Company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 8, 15, 30, 50],
          "level": 0,
          "idIndex": 7,
          "mortaged": false,
          "description":
              "Epic water company in the world. You have to do the rent times the dice eyes.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "You are having a stare battle with the sheriff.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": 4279060385,
          "tableColor": 4294953512
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": -200,
          "level": 0,
          "idIndex": 4,
          "mortaged": false,
          "description": "You stuck gold and receive £200!",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": 4294953512
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "DB",
          "name": "Crow's Canyon",
          "price": 100,
          "hyp": 175,
          "housePrice": 150,
          "rent": [10, 20, 35, 50, 60, 70, 90, 175, 500, 1100, 1300, 1500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description":
              "Crow's Ville is a rural town next to a canyon. It does have potential given enough funding.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "DB",
          "name": "Crow's Ville",
          "price": 100,
          "hyp": 200,
          "housePrice": 150,
          "rent": [50, 10, 20, 35, 50, 60, 70, 90, 200, 600, 1400, 1700, 2000],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description":
              "Crow's Ville is a rural town next to a canyon. It does have potential given enough funding.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        }
      ],
      "settings": {
        "name": "Game 1",
        "remotelyBuild": true,
        "goBonus": 200,
        "maxTurnes": 99999,
        "mustAuction": false,
        "startingMoney": 1500,
        "hackerScreen": false,
        "interest": 5,
        "dtlPrice": 2000,
        "startProperties": 0,
        "transportPassGo": false,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": false,
        "receiveProperties": true,
      },
      "extensions": ["transportation"],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true,
        "finished": null
      },
      "rentPayed": false,
      "findingsIndex": 1,
      "eventIndex": 5,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0.4.2",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "preset": "io.78.filorux.test",
      "tableColor": 4294953512
    },
    "infoCards": [],
    "primaryColor": 4290721292,
    "accentColor": 4294951175,
    "template": "default.trainstations"
  }
];
