import 'package:plutopoly/store/default_presets_data.dart';

const List<Map<String, dynamic>> land1Data = [
  {
    "title": "classic 1",
    "description": null,
    "author": "filorux",
    "projectName": "adventure.classic.1",
    "version": "0.0.1",
    "dataCache": {
      "running": false,
      "players": [
        {
          "name": "bot 0",
          "money": 2000.0,
          "position": 0,
          "color": 4280391411,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1500.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
        },
        {
          "name": "bot 1",
          "money": 1500.0,
          "position": 0,
          "color": 4294924066,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1500.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 0.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 1",
          "price": 60,
          "hyp": 30,
          "housePrice": 50,
          "rent": [2, 10, 30, 90, 160, 250],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 2",
          "price": 60,
          "hyp": 30,
          "housePrice": 50,
          "rent": [4, 20, 60, 180, 320, 450],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 200,
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 200],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light blue 1",
          "price": 100,
          "hyp": 50,
          "housePrice": 50,
          "rent": [6, 30, 90, 270, 400, 550],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 2",
          "price": 100,
          "hyp": 50,
          "housePrice": 50,
          "rent": [6, 30, 90, 270, 400, 550],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 3",
          "price": 120,
          "hyp": 60,
          "housePrice": 50,
          "rent": [8, 40, 100, 300, 450, 600],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 1",
          "price": 140,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Elektric Company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 2",
          "price": 140,
          "hyp": 70,
          "housePrice": 100,
          "rent": [10, 50, 150, 450, 625, 750],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 3",
          "price": 160,
          "hyp": 80,
          "housePrice": 100,
          "rent": [12, 60, 180, 500, 700, 900],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 2",
          "price": 200,
          "rent": [25, 50, 100, 250],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 1",
          "price": 180,
          "hyp": 90,
          "housePrice": 100,
          "rent": [14, 70, 200, 550, 750, 950],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 2",
          "price": 180,
          "hyp": 90,
          "housePrice": 100,
          "rent": [14, 70, 200, 550, 750, 950],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 3",
          "price": 200,
          "hyp": 100,
          "housePrice": 100,
          "rent": [16, 80, 220, 600, 800, 1000],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 1",
          "price": 220,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 2",
          "price": 220,
          "hyp": 110,
          "housePrice": 150,
          "rent": [18, 90, 250, 700, 875, 1050],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 3",
          "price": 240,
          "hyp": 120,
          "housePrice": 150,
          "rent": [20, 100, 300, 750, 925, 1100],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 3",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 250],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 1",
          "price": 260,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 2",
          "price": 260,
          "hyp": 130,
          "housePrice": 150,
          "rent": [22, 110, 330, 800, 975, 1150],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 3",
          "price": 280,
          "hyp": 140,
          "housePrice": 150,
          "rent": [24, 120, 360, 850, 1025, 1200],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 1",
          "price": 300,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1275],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 2",
          "price": 300,
          "hyp": 150,
          "housePrice": 200,
          "rent": [26, 130, 390, 900, 1100, 1250],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 3",
          "price": 320,
          "hyp": 160,
          "housePrice": 200,
          "rent": [28, 150, 450, 1000, 1200, 1400],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 4",
          "price": 200,
          "hyp": 100,
          "rent": [25, 50, 100, 250],
          "level": 0,
          "idIndex": 4,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 1",
          "price": 350,
          "hyp": 175,
          "housePrice": 200,
          "rent": [35, 175, 500, 1100, 1300, 1500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 2",
          "price": 400,
          "hyp": 200,
          "housePrice": 200,
          "rent": [50, 200, 600, 1400, 1700, 2000],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        }
      ],
      "settings": {
        "name": "",
        "remotelyBuild": true,
        "goBonus": 200,
        "maxTurnes": 99999,
        "mustAuction": false,
        "startingMoney": 1500,
        "hackerScreen": false,
        "interest": 5,
        "dtlPrice": 2000,
        "startProperties": 0,
        "transportPassGo": true,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": true,
        "receiveProperties": true
      },
      "extensions": [],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true
      },
      "rentPayed": false,
      "findingsIndex": 0,
      "eventIndex": 0,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "preset": "net.76.Testy.classic 1",
      "currency": "£",
      "placeCurrencyInFront": true
    },
    "infoCards": [],
    "primaryColor": null,
    "accentColor": null,
    "template": "classic"
  },
  {
    "title": "classic 2",
    "description": null,
    "author": "filorux",
    "projectName": "adventure.classic.2",
    "version": "0.0.1",
    "dataCache": {
      "running": false,
      "players": [
        {
          "name": "bot 1",
          "money": 1480.0,
          "position": 0,
          "color": 4294947584,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1500.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "description": null}
        },
        {
          "name": "bot 2",
          "money": 1500.0,
          "position": 0,
          "color": 4293467747,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1500.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "description": null}
        },
        {
          "name": "bot 3",
          "money": 1500.0,
          "position": 0,
          "color": 4288423856,
          "properties": [],
          "jailed": false,
          "jailTries": 0,
          "goojCards": 0,
          "info": [
            {"title": "New game", "leading": "i"}
          ],
          "moneyHistory": [0.0, 1500.0],
          "code": -2,
          "debt": 0.0,
          "loans": [],
          "stock": {},
          "ai": {"type": "normal", "description": null}
        }
      ],
      "currentPlayer": 0,
      "turn": 1,
      "currentDices": [1, -1],
      "doublesThrown": 0,
      "pot": 100.0,
      "gmap": [
        {
          "type": "start",
          "idPrefix": "TileType.start",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 1",
          "price": 60,
          "hyp": 30,
          "housePrice": 40,
          "rent": [30, 90, 160, 250, 350, 400],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4286141768,
          "idPrefix": "Br",
          "name": "Brown 2",
          "price": 60,
          "hyp": 30,
          "housePrice": 40,
          "rent": [60, 180, 320, 450, 550, 650],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 199,
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 1",
          "price": 200,
          "hyp": 100,
          "rent": [50, 100, 200, 350],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light blue 1",
          "price": 100,
          "hyp": 50,
          "housePrice": 40,
          "rent": [30, 90, 270, 400, 550, 650],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 2",
          "price": 100,
          "hyp": 50,
          "housePrice": 40,
          "rent": [30, 90, 270, 400, 550, 650],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4278430196,
          "idPrefix": "LB",
          "name": "Light Blue 3",
          "price": 120,
          "hyp": 60,
          "housePrice": 40,
          "rent": [40, 100, 300, 450, 600, 700],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "jail",
          "idPrefix": "JAIL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 1",
          "price": 140,
          "hyp": 70,
          "housePrice": 50,
          "rent": [50, 150, 450, 625, 750, 850],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Elektric Company",
          "price": 300,
          "hyp": 200,
          "rent": [15, 40],
          "level": 0,
          "idIndex": 1,
          "mortaged": true,
          "description":
              "The electricity is very expensive but the company needs to be fixed up.",
          "transportationPrice": 200,
          "backgroundColor": null,
          "icon": "bolt",
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 2",
          "price": 140,
          "hyp": 70,
          "housePrice": 50,
          "rent": [50, 150, 450, 625, 750, 850],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4288423856,
          "idPrefix": "P",
          "name": "Purple 3",
          "price": 160,
          "hyp": 80,
          "housePrice": 70,
          "rent": [60, 180, 500, 700, 900, 1000],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 2",
          "price": 200,
          "rent": [50, 100, 250, 350],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 1",
          "price": 180,
          "hyp": 90,
          "housePrice": 50,
          "rent": [70, 200, 550, 750, 950, 1000],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 2",
          "price": 180,
          "hyp": 90,
          "housePrice": 50,
          "rent": [70, 200, 550, 750, 950, 1000],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294940672,
          "idPrefix": "O",
          "name": "Orange 3",
          "price": 200,
          "hyp": 100,
          "housePrice": 70,
          "rent": [80, 220, 600, 800, 1000, 1100],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "parking",
          "idPrefix": "PARK",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 1",
          "price": 220,
          "hyp": 110,
          "housePrice": 100,
          "rent": [90, 250, 700, 875, 1050, 1200],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 2",
          "price": 220,
          "hyp": 110,
          "housePrice": 100,
          "rent": [90, 250, 700, 875, 1050, 1200],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294198070,
          "idPrefix": "R",
          "name": "Red 3",
          "price": 240,
          "hyp": 120,
          "housePrice": 120,
          "rent": [100, 300, 750, 925, 1100, 1250],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "color": 4294951175,
          "idPrefix": "T",
          "name": "Trainstation 3",
          "price": 350,
          "hyp": 100,
          "rent": [100, 250, 400, 550],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 1",
          "price": 260,
          "hyp": 130,
          "housePrice": 100,
          "rent": [110, 330, 800, 975, 1150, 1200],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 2",
          "price": 260,
          "hyp": 130,
          "housePrice": 100,
          "rent": [110, 330, 800, 975, 1150, 1200],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "company",
          "idPrefix": "C",
          "name": "Water company",
          "price": 150,
          "hyp": 75,
          "rent": [4, 10],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4294951175,
          "idPrefix": "Y",
          "name": "Yellow 3",
          "price": 280,
          "hyp": 140,
          "housePrice": 120,
          "rent": [120, 360, 850, 1025, 1200, 1250],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "police",
          "idPrefix": "POL",
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 1",
          "price": 300,
          "hyp": 150,
          "housePrice": 150,
          "rent": [130, 390, 900, 1100, 1275, 1300],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 2",
          "price": 300,
          "hyp": 150,
          "housePrice": 150,
          "rent": [130, 390, 900, 1100, 1250, 1300],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chest",
          "color": 4294967295,
          "idPrefix": "CC",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4283215696,
          "idPrefix": "G",
          "name": "Green 3",
          "price": 320,
          "hyp": 160,
          "housePrice": 170,
          "rent": [150, 450, 1000, 1200, 1400, 1500],
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "trainstation",
          "idPrefix": "T",
          "name": "Trainstation 4",
          "price": 200,
          "hyp": 100,
          "rent": [50, 100, 250, 350],
          "level": 0,
          "idIndex": 4,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "chance",
          "idPrefix": "Ch",
          "level": 0,
          "idIndex": 3,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 1",
          "price": 350,
          "hyp": 175,
          "housePrice": 150,
          "rent": [175, 500, 1100, 1300, 1400, 1500],
          "level": 0,
          "idIndex": 1,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "tax",
          "idPrefix": "tax",
          "price": 100,
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        },
        {
          "type": "land",
          "color": 4279060385,
          "idPrefix": "DB",
          "name": "Dark Blue 2",
          "price": 400,
          "hyp": 200,
          "housePrice": 170,
          "rent": [200, 600, 1400, 1700, 1900, 2100],
          "level": 0,
          "idIndex": 2,
          "mortaged": false,
          "description": "No info",
          "transportationPrice": 200,
          "backgroundColor": null,
          "tableColor": null
        }
      ],
      "settings": {
        "name": "Adventure game",
        "remotelyBuild": false,
        "goBonus": 200,
        "maxTurnes": 70,
        "mustAuction": false,
        "startingMoney": 500,
        "hackerScreen": false,
        "interest": 5,
        "dtlPrice": 2000,
        "startProperties": 4,
        "transportPassGo": true,
        "allowDiceSelect": false,
        "allowPriceChanges": false,
        "generateNames": true,
        "receiveProperties": true
      },
      "extensions": ["bank"],
      "ui": {
        "screenState": "idle",
        "showDealScreen": false,
        "shouldMove": true
      },
      "rentPayed": false,
      "findingsIndex": 0,
      "eventIndex": 0,
      "mapConfiguration": "classic",
      "dealData": {
        "payAmount": 0,
        "receivableProperties": [],
        "receiveProperties": [],
        "payableProperties": [],
        "payProperties": [],
        "price": 0,
        "valid": [true, true],
        "playerChecked": false,
        "dealerChecked": false,
        "dealer": null
      },
      "version": "0.5.3",
      "lostPlayers": [],
      "bot": false,
      "transported": false,
      "currency": "£",
      "placeCurrencyInFront": true
    },
    "infoCards": [
      {
        "title": "Base rent prices",
        "content":
            "The base rent prices have gone up for all properties including companies, trainstations, ...",
        "type": "tip"
      }
    ],
    "primaryColor": null,
    "accentColor": null,
    "template": "classic"
  },
  aiExample,
  {"Shuffled default map": null},
  largeClassic
];
