const List<String> MAP_NAMES = [
  """Mount Wo""",
  """Mount Wo is a small town at the foot of a mountain. It is known for a great train robbery.""",
  """Royal Ledlanwol""",
  """Royal Ledlanwol is a sprawling town, known for its car factory.""",
  """Wyacam Forest""",
  """Wyacam Forest is a large city, known for its elaborate legends.""",
  """Grand Winggon""",
  """Grand Winggon is a sprawling town, known for its space programme.""",
  """Monturai Harbour""",
  """Monturai Harbour is a small town, known for its palace.""",
  """Mircai End""",
  """Mircai End is a small town, known for its ghost stories.""",
  """Bridgat""",
  """Bridgat is a small town, known for its culture.""",
  """Grand Mslow""",
  """Grand Mslow is a large city, known for the battle of Grand Mslow.""",
  """Red Grenyard""",
  """Red Grenyard is a small city, known for its tech industry.""",
  """Ldavangate""",
  """Ldavangate is a large town, known for a great train robbery.""",
  """Lesbeyan""",
  """Lesbeyan is a sprawling city, known for its ghost stories.""",
  """West Grealdon""",
  """West Grealdon is a large town, known for tourism.""",
  """Zesalong Lake""",
  """Zesalong Lake is a small town situated besides a lake. It is known for a great train robbery.""",
  """St Rywichshey""",
  """St Rywichshey is a small town named after Saint Rywichshey. It is known for its nightlife.""",
  """Santa Rkhamclear""",
  """Santa Rkhamclear is a sprawling town named after Saint Rkhamclear. It is known for a famous invention.""",
  """South Sionyork""",
  """South Sionyork is a small town, known for gansters.""",
  """Royal Tawry""",
  """Royal Tawry is a sprawling town, known for elopement.""",
  """Manssmyton""",
  """Manssmyton is a large city, known for its nightlife.""",
  """Blyrich Du Thamenersworth""",
  """Blyrich Du Thamenersworth is a small city, known for a famous invention.""",
  """Mosfast Du Machigh""",
  """Mosfast Du Machigh is a small town, known for elopement.""",
  """Royal Chardgold""",
  """Royal Chardgold is a small town, known for gansters.""",
  """Halcranfortworth""",
  """Halcranfortworth is a sprawling town, known for inventing the Halcranfortworth cake.""",
  """Santa Chybathlox""",
  """Santa Chybathlox is a sprawling city named after Saint Chybathlox. It is known for being the birthplace of a famous author.""",
  """New Ntwichhor""",
  """New Ntwichhor is a large town, known for a famous invention.""",
  """Turesur""",
  """Turesur is a sprawling town, known for its arena.""",
  """San Maltba""",
  """San Maltba is a small town named after Saint Maltba. It is known for its cheese exportation.""",
  """West Xnardpriest""",
  """West Xnardpriest is a small city, known for its university.""",
  """Naldcombexbyside""",
  """Naldcombexbyside is a small town, known for its historic significance.""",
  """Rilfield""",
  """Rilfield is a small town, known for UFO reports.""",
  """Radon Park""",
  """Radon Park is a sprawling city, known for its chocolate.""",
  """Tiof Bend""",
  """Tiof Bend is a sprawling town, known for its mining heritage.""",
  """Las Prechiencus""",
  """Las Prechiencus is a sprawling town, known for its cheese exportation.""",
  """Red Chriraw""",
  """Red Chriraw is a small town, known for its tech industry.""",
  """Uck""",
  """Uck is a large city, known for theatre.""",
  """Nawprice Falls""",
  """Nawprice Falls is a small town, known for being the setting of a famous story.""",
  """Grandpaign Hill""",
  """Grandpaign Hill is a small town, known for tourism.""",
  """Wkernebee""",
  """Wkernebee is a sprawling city, known for the Wkernebee music festival.""",
  """Smiirthl""",
  """Smiirthl is a sprawling city, known for its university.""",
  """Thounogan""",
  """Thounogan is a large town, known for the Thounogan music festival.""",
  """Mcluis""",
  """Mcluis is a sprawling town, known for the Mcluis music festival.""",
  """Stockkyasea""",
  """Stockkyasea is a coastal, small town, known for its sports team.""",
  """Hampcum-In-Foyspawich""",
  """Hampcum-In-Foyspawich is a sprawling town, known for its research lab.""",
  """East Bro""",
  """East Bro is a large town, known for its sports team.""",
  """Rithbrack""",
  """Rithbrack is a small town, known for its tech industry.""",
  """Fort Lingbrika""",
  """Fort Lingbrika is a large town, known for UFO reports.""",
  """Park Rinesspa""",
  """Park Rinesspa is a sprawling town, known for its tech industry.""",
  """West Marshnorth""",
  """West Marshnorth is a sprawling town, known for its historic significance.""",
  """North Geeneau Aux Carlwe""",
  """North Geeneau Aux Carlwe is a small town, known for its castle.""",
  """Shikmul Aux Wathmor Haven""",
  """Shikmul Aux Wathmor Haven is a large town, known for tourism.""",
  """Grand Wywayne""",
  """Grand Wywayne is a small town, known for being the birthplace of a film star.""",
  """Xegreencey""",
  """Xegreencey is a sprawling town, known for its cheese exportation.""",
  """Didwkinge Castle""",
  """Didwkinge Castle is a small town, known for tourism.""",
  """Sounddamlooespa""",
  """Sounddamlooespa is a sprawling town, known for a great train robbery.""",
  """Stonetionchine""",
  """Stonetionchine is a sprawling city, known for gansters.""",
  """Port Farnfu Upon Rkethouse""",
  """Port Farnfu Upon Rkethouse is a coastal, small town, known for its research lab.""",
  """Red Tycoeur""",
  """Red Tycoeur is a sprawling city, known for its university.""",
  """Port Tenclausheights""",
  """Port Tenclausheights is a coastal, sprawling town, known for being the birthplace of a famous detective.""",
  """Las Aykit""",
  """Las Aykit is a large town, known for its culture.""",
  """Ber City""",
  """Ber City is a small town, known for its elaborate legends.""",
  """Moechester""",
  """Moechester is a small town, known for its palace.""",
  """Thorpehorslumb""",
  """Thorpehorslumb is a sprawling town, known for its space programme.""",
  """Brentvens""",
  """Brentvens is a sprawling town, known for its cheese exportation.""",
  """Red Stamarnon""",
  """Red Stamarnon is a small city, known for its nightlife.""",
  """Fairhe""",
  """Fairhe is a small town, known for tourism.""",
  """South Linplains""",
  """South Linplains is a sprawling town, known for UFO reports.""",
  """Mount Perthcalne""",
  """Mount Perthcalne is a sprawling town at the foot of a mountain. It is known for its historic significance.""",
  """Woodsterminster""",
  """Woodsterminster is a sprawling town, known for its nightlife.""",
  """Sidenkridgeko""",
  """Sidenkridgeko is a large town, known for progressive values.""",
  """Kentstroodley""",
  """Kentstroodley is a small city, known for its elaborate legends.""",
  """Saint Postrkerken""",
  """Saint Postrkerken is a sprawling town, known for its arena.""",
  """San Montcoorte-In-Grangenab""",
  """San Montcoorte-In-Grangenab is a sprawling town named after Saint Montcoorte. It is known for the San Montcoorte-In-Grangenab music festival.""",
  """Boyaburgh""",
  """Boyaburgh is a sprawling town, known for being the birthplace of a famous detective.""",
  """Las Lemdge""",
  """Las Lemdge is a large town, known for its research lab.""",
  """Jothbucombe""",
  """Jothbucombe is a large town, known for its historic significance.""",
  """Pethhapsing""",
  """Pethhapsing is a large city, known for its culture.""",
  """La Pa""",
  """La Pa is a small town, known for its nightlife.""",
  """East Chettmente""",
  """East Chettmente is a small town, known for a great train robbery.""",
  """Stonesmiththe Under Hiti""",
  """Stonesmiththe Under Hiti is a small town, known for inventing the Stonesmiththe Under Hiti cake.""",
  """Moose Roo""",
  """Moose Roo is a small city, known for a great train robbery.""",
  """La Moorstianking""",
  """La Moorstianking is a small town, known for inventing the La Moorstianking cake.""",
  """Hullpo-By-The-Sea""",
  """Hullpo-By-The-Sea is a coastal, large city, known for UFO reports.""",
  """Stonenettesed""",
  """Stonenettesed is a sprawling town, known for its mention in a famous song.""",
  """Ldeanspringley""",
  """Ldeanspringley is a large town, known for its sports team.""",
  """Rdeauke""",
  """Rdeauke is a large town, known for its palace.""",
  """Vilattve Beach""",
  """Vilattve Beach is a coastal, large town, known for being the birthplace of a music genre.""",
  """Dul""",
  """Dul is a large town, known for its elaborate legends.""",
  """Lake Minroy""",
  """Lake Minroy is a large city situated besides a lake. It is known for being the setting of a famous story.""",
  """Grand Saswer""",
  """Grand Saswer is a large town, known for the battle of Grand Saswer.""",
  """Bourgcham""",
  """Bourgcham is a sprawling town, known for its chocolate.""",
  """Port Ron""",
  """Port Ron is a coastal, small town, known for theatre.""",
  """La Ili""",
  """La Ili is a sprawling town, known for a famous invention.""",
  """Saint Kinsspri""",
  """Saint Kinsspri is a small town, known for conservative values.""",
  """El Nenan-In-Burnul""",
  """El Nenan-In-Burnul is a sprawling town, known for inventing the El Nenan-In-Burnul cake.""",
  """Phia""",
  """Phia is a sprawling town, known for being the birthplace of a music genre.""",
  """Alwkes Du Dulphblack""",
  """Alwkes Du Dulphblack is a large town, known for its cheese exportation.""",
  """Welchglos""",
  """Welchglos is a large town, known for being the birthplace of a film star.""",
  """West Pelday""",
  """West Pelday is a large town, known for its chocolate.""",
  """Lake Worthkeynlons""",
  """Lake Worthkeynlons is a small town situated besides a lake. It is known for its castle.""",
  """South Rna""",
  """South Rna is a small city, known for a great train robbery.""",
  """Saint Monterace""",
  """Saint Monterace is a sprawling town, known for the Saint Monterace music festival.""",
  """Moose Land""",
  """Moose Land is a large town, known for its mining heritage.""",
  """Prince Newich With Slandwil""",
  """Prince Newich With Slandwil is a large town, known for its palace.""",
  """Grand Rna""",
  """Grand Rna is a large city, known for the Grand Rna music festival.""",
  """Saint Arngeles""",
  """Saint Arngeles is a large town, known for its castle.""",
  """Co""",
  """Co is a sprawling city, known for a famous invention.""",
  """Wihamp""",
  """Wihamp is a sprawling town, known for its chocolate.""",
  """Wstonpidland""",
  """Wstonpidland is a large city, known for tourism.""",
  """Pierrersip""",
  """Pierrersip is a large city, known for its car factory.""",
  """Liscro Lake""",
  """Liscro Lake is a sprawling town situated besides a lake. It is known for being the birthplace of a famous detective.""",
  """East Relli""",
  """East Relli is a sprawling town, known for its tech industry.""",
  """Port Wkenles""",
  """Port Wkenles is a coastal, sprawling town, known for conservative values.""",
  """San Bythorn""",
  """San Bythorn is a small town named after Saint Bythorn. It is known for its tech industry.""",
  """Mount Ulmed Under Bolsun""",
  """Mount Ulmed Under Bolsun is a small city at the foot of a mountain. It is known for its arena.""",
  """Finkinlege City""",
  """Finkinlege City is a large town, known for a great train robbery.""",
  """West Nablika""",
  """West Nablika is a large town, known for its palace.""",
  """Fort Berking""",
  """Fort Berking is a sprawling town, known for its space programme.""",
  """New Hurstpar""",
  """New Hurstpar is a sprawling town, known for its sports team.""",
  """South Earrah Aux Nesainte""",
  """South Earrah Aux Nesainte is a small town, known for its space programme.""",
  """Droistegates""",
  """Droistegates is a sprawling town, known for its mention in a famous song.""",
  """Prince Racegate""",
  """Prince Racegate is a sprawling city, known for its elaborate legends.""",
  """New Nyardbatt""",
  """New Nyardbatt is a large town, known for its university.""",
  """Niyate""",
  """Niyate is a sprawling town, known for progressive values.""",
  """Thamekia""",
  """Thamekia is a large town, known for its historic significance.""",
  """Lake Lynnthe""",
  """Lake Lynnthe is a sprawling city situated besides a lake. It is known for elopement.""",
  """Og""",
  """Og is a small town, known for its mention in a famous song.""",
  """Beythy Haven""",
  """Beythy Haven is a sprawling town, known for its university.""",
  """Fort Middphur""",
  """Fort Middphur is a small town, known for its sports team.""",
  """Hopegerwkerne""",
  """Hopegerwkerne is a sprawling city, known for its arena.""",
  """Mirstang""",
  """Mirstang is a sprawling town, known for its historic significance.""",
  """Pockborne""",
  """Pockborne is a large town, known for its tech industry.""",
  """Bea""",
  """Bea is a sprawling town, known for the Bea music festival.""",
  """Raundsgains""",
  """Raundsgains is a large town, known for a famous invention.""",
  """Thtonsear Harbour""",
  """Thtonsear Harbour is a coastal, sprawling town, known for its nightlife.""",
  """La Moswers""",
  """La Moswers is a large city, known for being the birthplace of a music genre.""",
  """Ftusrysgates""",
  """Ftusrysgates is a sprawling city, known for progressive values.""",
  """East Seachel""",
  """East Seachel is a coastal, sprawling town, known for its sports team.""",
  """Tumin""",
  """Tumin is a small city, known for its culture.""",
  """New Nishplatte""",
  """New Nishplatte is a small town, known for its mention in a famous song.""",
  """West Edgefoldmoo""",
  """West Edgefoldmoo is a large town, known for progressive values.""",
  """North Tetdimare""",
  """North Tetdimare is a sprawling town, known for the North Tetdimare music festival.""",
  """Lake Azpauls""",
  """Lake Azpauls is a small town situated besides a lake. It is known for its tech industry.""",
  """Gaigeorge""",
  """Gaigeorge is a large town, known for the battle of Gaigeorge.""",
  """Mount Tainmyrttworth""",
  """Mount Tainmyrttworth is a large town at the foot of a mountain. It is known for its elaborate legends.""",
  """West Lowsas""",
  """West Lowsas is a large town, known for its nightlife.""",
  """Xecharpool""",
  """Xecharpool is a sprawling city, known for inventing the Xecharpool cake.""",
  """Tsongrosse""",
  """Tsongrosse is a small city, known for being the birthplace of a film star.""",
  """Grand Havthorpecoorte""",
  """Grand Havthorpecoorte is a sprawling city, known for the battle of Grand Havthorpecoorte.""",
  """Pyside Forest""",
  """Pyside Forest is a sprawling city, known for a famous invention.""",
  """Lutwhit""",
  """Lutwhit is a large town, known for being the birthplace of a music genre.""",
  """East Cawales""",
  """East Cawales is a small town, known for its palace.""",
  """Fort Longbridar""",
  """Fort Longbridar is a large city, known for progressive values.""",
  """Reclea Springs""",
  """Reclea Springs is a sprawling town situated at the source of a river. It is known for gansters.""",
  """North Nallarread""",
  """North Nallarread is a small town, known for inventing the North Nallarread cake.""",
  """Chardlang""",
  """Chardlang is a sprawling town, known for its palace.""",
  """Tonold End""",
  """Tonold End is a small town, known for its arena.""",
  """West Brookchajohns""",
  """West Brookchajohns is a large town, known for UFO reports.""",
  """Lybor""",
  """Lybor is a sprawling town, known for its castle.""",
  """Tin""",
  """Tin is a large city, known for its culture.""",
  """Royal Bajdid""",
  """Royal Bajdid is a small town, known for the battle of Royal Bajdid.""",
  """Rslempor""",
  """Rslempor is a large town, known for gansters.""",
  """Longnto""",
  """Longnto is a large town, known for its research lab.""",
  """Soufairca Falls""",
  """Soufairca Falls is a small town, known for its mention in a famous song.""",
  """Grand Bornewar""",
  """Grand Bornewar is a sprawling city, known for its car factory.""",
  """New Hargridge""",
  """New Hargridge is a small city, known for its space programme.""",
  """West Grandthern""",
  """West Grandthern is a large city, known for its arena.""",
  """North Cruces""",
  """North Cruces is a small city, known for being the setting of a famous story.""",
  """Royal Sladewo""",
  """Royal Sladewo is a large city, known for UFO reports.""",
  """Mondbuckhead""",
  """Mondbuckhead is a large city, known for conservative values.""",
  """Ntaineshepjuan""",
  """Ntaineshepjuan is a large town, known for its arena.""",
  """Grand Phenwer""",
  """Grand Phenwer is a large town, known for being the birthplace of a music genre.""",
  """Moose Thunntown""",
  """Moose Thunntown is a small town, known for its arena.""",
  """Cushal""",
  """Cushal is a large town, known for its nightlife.""",
  """Piyelhampton""",
  """Piyelhampton is a small town situated on a river bend known for the battle of Piyelhampton.""",
  """Ladgar With Cotesxeham""",
  """Ladgar With Cotesxeham is a small town, known for its research lab.""",
  """San Smithblo""",
  """San Smithblo is a small city named after Saint Smithblo. It is known for a great train robbery.""",
  """Chedochesrolington""",
  """Chedochesrolington is a small town, known for a famous invention.""",
  """South Bour""",
  """South Bour is a large town, known for its historic significance.""",
  """Putsou""",
  """Putsou is a sprawling town, known for its historic significance.""",
  """Cape Wad""",
  """Cape Wad is a sprawling city, known for its nightlife.""",
  """Fort Rossjim""",
  """Fort Rossjim is a sprawling town, known for its car factory.""",
  """Las Newroyal""",
  """Las Newroyal is a small city, known for its cheese exportation.""",
  """La Radcrook""",
  """La Radcrook is a small city, known for its mining heritage.""",
  """West Rdiete""",
  """West Rdiete is a sprawling town, known for its car factory.""",
  """Lockvenchester""",
  """Lockvenchester is a large town, known for its university.""",
  """Campgoullansford""",
  """Campgoullansford is a large town, known for the Campgoullansford music festival.""",
  """Fort Briggvey""",
  """Fort Briggvey is a small city, known for its car factory.""",
  """El Chu""",
  """El Chu is a large town, known for its arena.""",
  """Las Vildeal""",
  """Las Vildeal is a small town, known for its sports team.""",
  """La Ntefer""",
  """La Ntefer is a large city, known for its car factory.""",
  """North Diacrerding Aux Stonetral""",
  """North Diacrerding Aux Stonetral is a sprawling town, known for its palace.""",
  """New Loshav Upon Headrnard""",
  """New Loshav Upon Headrnard is a large city, known for its arena.""",
  """Moose Rseymergin""",
  """Moose Rseymergin is a small city, known for gansters.""",
  """Borro Aux Vieveniegate""",
  """Borro Aux Vieveniegate is a small town, known for its culture.""",
  """Grand Plainscke""",
  """Grand Plainscke is a small town, known for the battle of Grand Plainscke.""",
  """San Swe""",
  """San Swe is a large town named after Saint Swe. It is known for its car factory.""",
  """El Pruddurnan""",
  """El Pruddurnan is a small town, known for conservative values.""",
  """West Zanaw""",
  """West Zanaw is a large town, known for its nightlife.""",
  """La Rna""",
  """La Rna is a large town, known for its sports team.""",
  """Fort Faelbrook""",
  """Fort Faelbrook is a small town, known for its nightlife.""",
  """San Shanwest With Wainpat""",
  """San Shanwest With Wainpat is a large town named after Saint Shanwest. It is known for its nightlife.""",
];
