import 'package:flutter/material.dart';
import 'package:plutopoly/helpers/money_helper.dart';

buildTrain(int index, [Color color]) {
  return {
    "type": "trainstation",
    "color": null,
    "idPrefix": "T",
    "name": "Trainstation $index",
    "price": 200,
    "hyp": 100,
    "housePrice": null,
    "rent": [25, 50, 100, 200],
    "level": 0,
    "idIndex": index,
    "mortaged": false,
    "description": null,
    "transportationPrice": 200,
  };
}

const Map<String, dynamic> largeClassic = {
  "title": "Large map",
  "description": "A large classic map.",
  "author": "filorux",
  "projectName": "default.large_classic",
  "version": "0.0.1",
  "dataCache": {
    "running": null,
    "players": [
      {
        "name": "bot 1",
        "money": 1500.0,
        "position": 0,
        "color": 4294947584,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
      },
      {
        "name": "bot 2",
        "money": 1500.0,
        "position": 0,
        "color": 4284955319,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
      },
      {
        "name": "bot 3",
        "money": 1500.0,
        "position": 0,
        "color": 4278190080,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
      },
      {
        "name": "bot 4",
        "money": 1500.0,
        "position": 0,
        "color": 4294947584,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "aiSettingsCache": null, "description": null}
      }
    ],
    "currentPlayer": 0,
    "turn": 1,
    "currentDices": [1, -1],
    "doublesThrown": 0,
    "pot": 0.0,
    "gmap": [
      {
        "type": "start",
        "idPrefix": "TileType.start",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4286141768,
        "idPrefix": "Br",
        "name": "Brown 1",
        "price": 60,
        "hyp": 30,
        "housePrice": 50,
        "rent": [2, 10, 30, 90, 160, 250, 300, 350, 450, 600, 800],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chest",
        "idPrefix": "CC",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4286141768,
        "idPrefix": "Br",
        "name": "Brown 2",
        "price": 60,
        "hyp": 30,
        "housePrice": 50,
        "rent": [4, 20, 60, 180, 320, 450, 500, 550, 650, 750, 900],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "tax",
        "idPrefix": "tax",
        "price": 200,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 1",
        "price": 200,
        "hyp": 100,
        "rent": [150, 200, 500, 1200, 2000],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4278430196,
        "idPrefix": "LB",
        "name": "Light blue 1",
        "price": 100,
        "hyp": 50,
        "housePrice": 50,
        "rent": [6, 30, 90, 270, 400, 550, 600, 650, 750, 850, 1000],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4278430196,
        "idPrefix": "LB",
        "name": "Light Blue 2",
        "price": 100,
        "hyp": 50,
        "housePrice": 50,
        "rent": [6, 30, 90, 270, 400, 550, 600, 650, 750, 850, 1000],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4278430196,
        "idPrefix": "LB",
        "name": "Light Blue 3",
        "price": 120,
        "hyp": 60,
        "housePrice": 50,
        "rent": [8, 40, 100, 300, 450, 600, 650, 700, 800, 900, 1100],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "jail",
        "idPrefix": "JAIL",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4288423856,
        "idPrefix": "P",
        "name": "Purple 1",
        "price": 140,
        "hyp": 70,
        "housePrice": 100,
        "rent": [10, 50, 150, 450, 625, 750, 800, 850, 950, 1150, 1300],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "company",
        "idPrefix": "C",
        "name": "Elektric Company",
        "price": 150,
        "hyp": 75,
        "rent": [4, 10, 30],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "icon": "bolt",
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4288423856,
        "idPrefix": "P",
        "name": "Purple 2",
        "price": 140,
        "hyp": 70,
        "housePrice": 100,
        "rent": [10, 50, 150, 450, 625, 750, 800, 850, 950, 1150, 1300],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4288423856,
        "idPrefix": "P",
        "name": "Purple 3",
        "price": 160,
        "hyp": 80,
        "housePrice": 100,
        "rent": [12, 60, 180, 500, 700, 900, 950, 1000, 1100, 1200, 1400],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 2",
        "price": 200,
        "rent": [150, 200, 500, 1200, 2000],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294940672,
        "idPrefix": "O",
        "name": "Orange 1",
        "price": 180,
        "hyp": 90,
        "housePrice": 100,
        "rent": [14, 70, 200, 550, 750, 950, 1000, 1050, 1150, 1300, 1500],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chest",
        "color": 4294967295,
        "idPrefix": "CC",
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294940672,
        "idPrefix": "O",
        "name": "Orange 2",
        "price": 180,
        "hyp": 90,
        "housePrice": 100,
        "rent": [14, 70, 200, 550, 750, 950, 1000, 1050, 1150, 1300, 1500],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294940672,
        "idPrefix": "O",
        "name": "Orange 3",
        "price": 200,
        "hyp": 100,
        "housePrice": 100,
        "rent": [16, 80, 220, 600, 800, 1000, 1050, 1150, 1250, 1350, 1600],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 1",
        "price": 200,
        "hyp": 100,
        "rent": [25, 50, 100, 200],
        "level": 0,
        "idIndex": 47,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "tax",
        "idPrefix": "tax",
        "price": -100,
        "level": 0,
        "idIndex": 49,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4284513675,
        "idPrefix": "Gr",
        "name": "Grey 2",
        "price": 300,
        "hyp": 150,
        "housePrice": 200,
        "rent": [26, 130, 390, 1100, 1275, 1400, 1450, 1500, 1600, 1800, 2000],
        "level": 0,
        "idIndex": 46,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 48,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4284513675,
        "idPrefix": "Gr",
        "name": "Grey 1",
        "price": 300,
        "hyp": 150,
        "housePrice": 200,
        "rent": [26, 130, 390, 1100, 1275, 1400, 1450, 1500, 1600, 1800, 2000],
        "level": 0,
        "idIndex": 45,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "parking",
        "idPrefix": "PARK",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294198070,
        "idPrefix": "R",
        "name": "Red 1",
        "price": 220,
        "hyp": 110,
        "housePrice": 150,
        "rent": [18, 90, 250, 700, 875, 1050, 1100, 1200, 1300, 1500, 1800],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294198070,
        "idPrefix": "R",
        "name": "Red 2",
        "price": 220,
        "hyp": 110,
        "housePrice": 150,
        "rent": [18, 90, 250, 700, 875, 1050, 1100, 1200, 1300, 1500, 1800],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294198070,
        "idPrefix": "R",
        "name": "Red 3",
        "price": 240,
        "hyp": 120,
        "housePrice": 150,
        "rent": [20, 100, 300, 750, 925, 1100, 1150, 1350, 1500, 1800, 2000],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 3",
        "price": 200,
        "hyp": 100,
        "rent": [150, 200, 500, 1200, 2000],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4293467747,
        "idPrefix": "Pu",
        "name": "Pink 1",
        "price": 220,
        "hyp": 110,
        "housePrice": 150,
        "rent": [18, 90, 250, 700, 875, 1050, 1150, 1300, 1500, 1700, 2000],
        "level": 0,
        "idIndex": 40,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "company",
        "color": 4283215696,
        "idPrefix": "C",
        "name": "Clean Elektric Company",
        "price": 200,
        "hyp": 75,
        "rent": [4, 10, 40],
        "level": 0,
        "idIndex": 44,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "icon": "bolt",
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4293467747,
        "idPrefix": "Pu",
        "name": "Pink 2",
        "price": 220,
        "hyp": 110,
        "housePrice": 150,
        "rent": [18, 90, 250, 700, 875, 1050, 1150, 1300, 1500, 1700, 2000],
        "level": 0,
        "idIndex": 41,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4293467747,
        "idPrefix": "Pu",
        "name": "Pink 3",
        "price": 220,
        "hyp": 110,
        "housePrice": 150,
        "rent": [18, 90, 250, 700, 875, 1050, 1200, 1400, 1600, 1900, 2200],
        "level": 0,
        "idIndex": 42,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 1",
        "price": 200,
        "hyp": 100,
        "rent": [150, 200, 500, 1200, 2000],
        "level": 0,
        "idIndex": 43,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Yellow 1",
        "price": 260,
        "hyp": 130,
        "housePrice": 150,
        "rent": [22, 110, 330, 800, 975, 1150, 1300, 1500, 1800, 2000, 2300],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Yellow 2",
        "price": 260,
        "hyp": 130,
        "housePrice": 150,
        "rent": [22, 110, 330, 800, 975, 1150, 1300, 1500, 1800, 2000, 2300],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "company",
        "idPrefix": "C",
        "name": "Water company",
        "price": 150,
        "hyp": 75,
        "rent": [4, 10, 30],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Yellow 3",
        "price": 280,
        "hyp": 140,
        "housePrice": 150,
        "rent": [24, 120, 360, 850, 1025, 1200, 1400, 1600, 1900, 2200, 2500],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "police",
        "idPrefix": "POL",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Green 1",
        "price": 300,
        "hyp": 150,
        "housePrice": 200,
        "rent": [26, 130, 390, 900, 1100, 1275, 1400, 1600, 1900, 2200, 2500],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Green 2",
        "price": 300,
        "hyp": 150,
        "housePrice": 200,
        "rent": [26, 130, 390, 900, 1100, 1275, 1400, 1600, 1900, 2200, 2500],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chest",
        "color": 4294967295,
        "idPrefix": "CC",
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Green 3",
        "price": 320,
        "hyp": 160,
        "housePrice": 200,
        "rent": [28, 150, 450, 1000, 1200, 1400, 1600, 1800, 2100, 2500, 3000],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "color": 4294951175,
        "idPrefix": "T",
        "name": "Trainstation 4",
        "price": 400,
        "hyp": 100,
        "rent": [150, 200, 500, 1200, 2000],
        "level": 0,
        "idIndex": 4,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4279060385,
        "idPrefix": "DB",
        "name": "Dark Blue 1",
        "price": 350,
        "hyp": 175,
        "housePrice": 200,
        "rent": [35, 175, 500, 1100, 1300, 1500, 1700, 1900, 2500, 2900, 3500],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "tax",
        "idPrefix": "tax",
        "price": 100,
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4279060385,
        "idPrefix": "DB",
        "name": "Dark Blue 2",
        "price": 400,
        "hyp": 200,
        "housePrice": 200,
        "rent": [50, 200, 600, 1400, 1700, 2000, 2200, 2500, 2800, 3400, 3800],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      }
    ],
    "settings": {
      "name": "",
      "remotelyBuild": true,
      "goBonus": 300,
      "maxTurnes": 99999,
      "mustAuction": false,
      "startingMoney": 2000,
      "hackerScreen": false,
      "interest": 5,
      "dtlPrice": 2000,
      "startProperties": 0,
      "transportPassGo": true,
      "allowDiceSelect": false,
      "allowPriceChanges": false,
      "generateNames": true
    },
    "extensions": ["bank", "stock"],
    "ui": {
      "screenState": "idle",
      "showDealScreen": false,
      "shouldMove": true,
      "finished": false
    },
    "rentPayed": false,
    "findingsIndex": 0,
    "eventIndex": 0,
    "mapConfiguration": "classic",
    "dealData": {
      "payAmount": 0,
      "receivableProperties": [],
      "receiveProperties": [],
      "payableProperties": [],
      "payProperties": [],
      "price": 0,
      "valid": [true, true],
      "playerChecked": false,
      "dealerChecked": false,
      "dealer": null
    },
    "version": "0",
    "lostPlayers": [],
    "bot": false,
    "transported": false,
    "preset": "web.76.Testy.classic 5",
    "currency": "£",
    "placeCurrencyInFront": true
  },
  "infoCards": [
    {
      "title": "double hotels",
      "content": "You can build up to 2 hotels on 1 tile.",
      "type": "rule"
    }
  ],
  "primaryColor": null,
  "accentColor": null,
  "template": "classic"
};

const Map<String, dynamic> aiExample = {
  "title": "AI example",
  "description": "An idle ai",
  "author": "filorux",
  "projectName": "default.ai_example",
  "version": "0.0.1",
  "dataCache": {
    "running": false,
    "players": [
      {
        "name": "bot 1",
        "money": 1500.0,
        "position": 0,
        "color": 4283215696,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "description": null}
      },
      {
        "name": "Idle bot",
        "money": 1500.0,
        "position": 0,
        "color": 4288423856,
        "properties": [
          "P:1",
          "P:2",
          "P:3",
        ],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {
          "type": "normal",
          "description": "Doesn't do anything.",
          "aiSettingsCache": {
            "chances": [0, 0, 1, 1, 0],
            "smart": false,
            "canTrade": false,
            "moneyFactor": 0.95,
          }
        }
      },
      {
        "name": "bot 2",
        "money": 1500.0,
        "position": 0,
        "color": 4294947584,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "description": "Hard BOT"}
      },
      {
        "name": "bot 3",
        "money": 1500.0,
        "position": 0,
        "color": 4294924066,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [
          {"title": "New game", "leading": "i"}
        ],
        "moneyHistory": [0.0, 1500.0],
        "code": -2,
        "debt": 0.0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal", "description": null}
      }
    ],
    "currentPlayer": 0,
    "turn": 1,
    "currentDices": [1, -1],
    "doublesThrown": 0,
    "pot": 0.0,
    "gmap": [
      {
        "type": "start",
        "idPrefix": "TileType.start",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4286141768,
        "idPrefix": "Br",
        "name": "Brown 1",
        "price": 50,
        "hyp": 30,
        "housePrice": 50,
        "rent": [2, 10, 30, 90, 160, 250],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chest",
        "idPrefix": "CC",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4286141768,
        "idPrefix": "Br",
        "name": "Brown 2",
        "price": 100,
        "hyp": 30,
        "housePrice": 50,
        "rent": [4, 20, 60, 180, 320, 450],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "tax",
        "idPrefix": "tax",
        "price": -200,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 1",
        "price": 200,
        "hyp": 100,
        "rent": [25, 50, 100, 200],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4278430196,
        "idPrefix": "LB",
        "name": "Light blue 1",
        "price": 100,
        "hyp": 50,
        "housePrice": 100,
        "rent": [6, 30, 90, 270, 400, 550],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4278430196,
        "idPrefix": "LB",
        "name": "Light Blue 2",
        "price": 100,
        "hyp": 50,
        "housePrice": 50,
        "rent": [6, 30, 90, 270, 400, 550],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4278430196,
        "idPrefix": "LB",
        "name": "Light Blue 3",
        "price": 200,
        "hyp": 60,
        "housePrice": 100,
        "rent": [8, 40, 100, 300, 450, 600],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "police",
        "idPrefix": "POL",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4288423856,
        "idPrefix": "P",
        "name": "Purple 1",
        "price": 150,
        "hyp": 70,
        "housePrice": 150,
        "rent": [10, 50, 150, 450, 625, 750],
        "level": 2,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "company",
        "idPrefix": "C",
        "name": "Elektric Company",
        "price": 150,
        "hyp": 75,
        "rent": [5, 10],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "icon": "bolt",
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4288423856,
        "idPrefix": "P",
        "name": "Purple 2",
        "price": 150,
        "hyp": 70,
        "housePrice": 150,
        "rent": [10, 50, 150, 450, 625, 750],
        "level": 2,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4288423856,
        "idPrefix": "P",
        "name": "Purple 3",
        "price": 250,
        "hyp": 80,
        "housePrice": 150,
        "rent": [12, 60, 180, 500, 700, 900],
        "level": 2,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 2",
        "price": 200,
        "rent": [25, 50, 100, 250],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294940672,
        "idPrefix": "O",
        "name": "Orange 1",
        "price": 180,
        "hyp": 90,
        "housePrice": 200,
        "rent": [14, 70, 200, 550, 750, 950],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chest",
        "color": 4294967295,
        "idPrefix": "CC",
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294940672,
        "idPrefix": "O",
        "name": "Orange 2",
        "price": 180,
        "hyp": 90,
        "housePrice": 200,
        "rent": [14, 70, 200, 550, 750, 950],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294940672,
        "idPrefix": "O",
        "name": "Orange 3",
        "price": 300,
        "hyp": 200,
        "housePrice": 100,
        "rent": [16, 80, 220, 600, 800, 1000],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "parking",
        "idPrefix": "PARK",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294198070,
        "idPrefix": "R",
        "name": "Red 1",
        "price": 220,
        "hyp": 110,
        "housePrice": 220,
        "rent": [18, 90, 250, 700, 875, 1050],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294198070,
        "idPrefix": "R",
        "name": "Red 2",
        "price": 220,
        "hyp": 110,
        "housePrice": 220,
        "rent": [18, 90, 250, 700, 875, 1050],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294198070,
        "idPrefix": "R",
        "name": "Red 3",
        "price": 350,
        "hyp": 120,
        "housePrice": 220,
        "rent": [20, 100, 300, 750, 925, 1100],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 3",
        "price": 200,
        "hyp": 100,
        "rent": [25, 50, 100, 250],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Yellow 1",
        "price": 260,
        "hyp": 130,
        "housePrice": 250,
        "rent": [22, 110, 330, 800, 975, 1150],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Yellow 2",
        "price": 260,
        "hyp": 130,
        "housePrice": 250,
        "rent": [22, 110, 330, 800, 975, 1150],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "company",
        "idPrefix": "C",
        "name": "Water company",
        "price": 150,
        "hyp": 75,
        "rent": [5, 10],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Yellow 3",
        "price": 400,
        "hyp": 140,
        "housePrice": 250,
        "rent": [24, 120, 360, 850, 1025, 1200],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "jail",
        "idPrefix": "JAIL",
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Green 1",
        "price": 300,
        "hyp": 150,
        "housePrice": 300,
        "rent": [26, 130, 390, 900, 1100, 1275],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Green 2",
        "price": 300,
        "hyp": 150,
        "housePrice": 300,
        "rent": [26, 130, 390, 900, 1100, 1250],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chest",
        "color": 4294967295,
        "idPrefix": "CC",
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Green 3",
        "price": 450,
        "hyp": 160,
        "housePrice": 300,
        "rent": [28, 150, 450, 1000, 1200, 1400],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "trainstation",
        "idPrefix": "T",
        "name": "Trainstation 4",
        "price": 200,
        "hyp": 100,
        "rent": [25, 50, 100, 250],
        "level": 0,
        "idIndex": 4,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "chance",
        "idPrefix": "Ch",
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4279060385,
        "idPrefix": "DB",
        "name": "Dark Blue 1",
        "price": 350,
        "hyp": 175,
        "housePrice": 350,
        "rent": [35, 175, 500, 1100, 1300, 1500],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "tax",
        "idPrefix": "tax",
        "price": -100,
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      },
      {
        "type": "land",
        "color": 4279060385,
        "idPrefix": "DB",
        "name": "Dark Blue 2",
        "price": 500,
        "hyp": 200,
        "housePrice": 350,
        "rent": [50, 200, 600, 1400, 1700, 2000],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "No info",
        "transportationPrice": 200,
        "backgroundColor": null,
        "tableColor": null
      }
    ],
    "settings": {
      "name": "",
      "remotelyBuild": true,
      "goBonus": 200,
      "maxTurnes": 99999,
      "mustAuction": false,
      "startingMoney": 500,
      "hackerScreen": false,
      "interest": 5,
      "dtlPrice": 2000,
      "startProperties": 0,
      "transportPassGo": true,
      "allowDiceSelect": false,
      "allowPriceChanges": false,
      "generateNames": true,
      "receiveProperties": true
    },
    "extensions": ["bank"],
    "ui": {"screenState": "idle", "showDealScreen": false, "shouldMove": true},
    "rentPayed": false,
    "findingsIndex": 0,
    "eventIndex": 0,
    "mapConfiguration": "classic",
    "dealData": {
      "payAmount": 0,
      "receivableProperties": [],
      "receiveProperties": [],
      "payableProperties": [],
      "payProperties": [],
      "price": 0,
      "valid": [true, true],
      "playerChecked": false,
      "dealerChecked": false,
      "dealer": null
    },
    "version": "0.5.3",
    "lostPlayers": [],
    "bot": false,
    "transported": false,
    "preset": "map.73.Testy.classic 3",
    "currency": "£",
    "placeCurrencyInFront": true
  },
  "infoCards": [
    {
      "title": "Expensive houses",
      "content": "Houses and some tiles are much more expensive.",
      "type": "alert"
    },
    {
      "title": "Idle bot",
      "content":
          "The idle bot doesn't build or buy anything. He does pay when he lands on a property.",
      "type": "rule"
    }
  ],
  "primaryColor": null,
  "accentColor": null,
  "template": "classic"
};

Map<String, dynamic> presetsData = {
  "default.trainstations": {
    "preset": "default.trainstations",
    "running": false,
    "players": [
      {
        "name": "Ricardo",
        "money": 1000,
        "position": 0,
        "color": Colors.cyan.value,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [],
        "moneyHistory": [],
        "code": -2,
        "debt": 0,
        "loans": [],
        "stock": {},
        "ai": {
          "type": "normal",
          "_aiSettings": {"idle": true}
        }
      },
      {
        "name": "August",
        "money": 1000,
        "position": 0,
        "color": Colors.blueGrey.value,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [],
        "moneyHistory": [],
        "code": -2,
        "debt": 0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal"}
      },
      {
        "name": "Daisy",
        "money": 1000,
        "position": 0,
        "color": Colors.deepPurple.value,
        "properties": [],
        "jailed": false,
        "jailTries": 0,
        "goojCards": 0,
        "info": [],
        "moneyHistory": [],
        "code": -2,
        "debt": 0,
        "loans": [],
        "stock": {},
        "ai": {"type": "normal"}
      }
    ],
    "currentPlayer": 0,
    "turn": 1,
    "currentDices": [1, -1],
    "doublesThrown": 0,
    "pot": 0,
    "gmap": [
      {
        "type": "start",
        "color": null,
        "idPrefix": "TileType.start",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "This is the start tile of the game.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Wallworth",
        "price": 350,
        "hyp": 130,
        "housePrice": 150,
        "rent": [22, 110, 330, 800, 975, 1150],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "A big city. Known for it's oil lamps.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "tax",
        "color": null,
        "idPrefix": "tax",
        "name": null,
        "price": -100,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "You bring in a bounty +${mon(100)}!",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Delinosa",
        "price": 350,
        "hyp": 130,
        "housePrice": 150,
        "rent": [22, 110, 330, 800, 975, 1150],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description":
            "A pretty large city. It had the first railway connection with Berbury.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      buildTrain(1, Colors.grey),
      buildTrain(2, Colors.grey),
      {
        "type": "land",
        "color": 4294951175,
        "idPrefix": "Y",
        "name": "Hastter",
        "price": 380,
        "hyp": 140,
        "housePrice": 150,
        "rent": [24, 120, 360, 850, 1025, 1200],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description":
            "The capital of the yellow street. Known for it's banking services.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "chance",
        "color": null,
        "idPrefix": "Ch",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": 4294922834,
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Greenworth",
        "price": 400,
        "hyp": 150,
        "housePrice": 200,
        "rent": [26, 130, 390, 900, 1100, 1275],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description":
            "A big city with a giant central park. Known for its cotton industry",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      buildTrain(3, Colors.grey),
      {
        "type": "police",
        "color": null,
        "idPrefix": "POL",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Tulman",
        "price": 400,
        "hyp": 150,
        "housePrice": 200,
        "rent": [26, 130, 390, 900, 1100, 1250],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "A grey city known for it's metal industry.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "chest",
        "idPrefix": "CC",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 0,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": 4279060385,
      },
      {
        "type": "land",
        "color": 4283215696,
        "idPrefix": "G",
        "name": "Berbury",
        "price": 450,
        "hyp": 160,
        "housePrice": 200,
        "rent": [28, 150, 450, 1000, 1200, 1400],
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description":
            "A pretty large city. It had the first railway connection with Delinosa.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      buildTrain(4, Colors.grey),
      buildTrain(5, Colors.grey),
      {
        "type": "company",
        "color": Colors.black.value,
        "idPrefix": "C",
        "name": "South coal mine",
        "icon": "bolt",
        "price": 150,
        "hyp": 75,
        "housePrice": null,
        "rent": [5, 10, 15, 30, 50],
        "level": 0,
        "idIndex": 0,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
      },
      {
        "type": "chance",
        "color": null,
        "idPrefix": "Ch",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "tax",
        "color": null,
        "idPrefix": "tax",
        "name": null,
        "price": 100,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": "You've been robbed by a bandid.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "company",
        "color": null,
        "idPrefix": "C",
        "name": "Dry Water company",
        "rent": [4, 8, 15, 30, 50],
        "price": 150,
        "hyp": 75,
        "housePrice": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description":
            "Best water company in the world. You have to do the rent times the dice eyes.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "tax",
        "color": null,
        "idPrefix": "tax",
        "name": null,
        "price": 100,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "land",
        "color": Colors.brown.value,
        "idPrefix": "O",
        "name": "Twin Scar 1",
        "price": 100,
        "hyp": 90,
        "housePrice": 100,
        "rent": [10, 20, 35, 50, 60, 70, 100, 200, 550, 750, 950],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description":
            "Twin scar is a rural outpost. It does have potential given enough funding.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "chance",
        "color": null,
        "idPrefix": "Ch",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 3,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "land",
        "color": Colors.brown.value,
        "idPrefix": "O",
        "name": "Twin Scar 2",
        "price": 100,
        "hyp": 90,
        "housePrice": 100,
        "rent": [10, 20, 35, 50, 60, 70, 100, 200, 550, 750, 950],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description":
            "Twin scar is a rural town full of coal miners. It does have potential given enough funding.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "company",
        "idPrefix": "C",
        "color": Colors.black.value,
        "name": "West coal mine",
        "icon": "bolt",
        "price": 150,
        "hyp": 75,
        "housePrice": null,
        "rent": [5, 10, 15, 30, 50],
        "level": 0,
        "idIndex": 5,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
      },
      buildTrain(6, Colors.yellow[700]),
      {
        "type": "company",
        "color": Colors.black.value,
        "idPrefix": "C",
        "name": "North coal mine",
        "price": 150,
        "hyp": 75,
        "housePrice": null,
        "rent": [5, 10, 15, 30, 50],
        "level": 0,
        "icon": "bolt",
        "idIndex": 6,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
      },
      {
        "type": "chest",
        "idPrefix": "CC",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": 4279060385,
      },
      {
        "type": "company",
        "color": null,
        "idPrefix": "C",
        "name": "Upper Water Company",
        "price": 150,
        "hyp": 75,
        "housePrice": null,
        "rent": [4, 8, 15, 30, 50],
        "level": 0,
        "idIndex": 7,
        "mortaged": false,
        "description":
            "Epic water company in the world. You have to do the rent times the dice eyes.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "jail",
        "color": null,
        "idPrefix": "JAIL",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": "You are having a stare battle with the sheriff.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "chest",
        "idPrefix": "CC",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": 4279060385,
      },
      {
        "type": "tax",
        "color": null,
        "idPrefix": "tax",
        "name": null,
        "price": -200,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 4,
        "mortaged": false,
        "description": "You stuck gold and receive ${mon(200)}!",
        "transportationPrice": 200,
      },
      {
        "type": "land",
        "color": Colors.red.value,
        "idPrefix": "DB",
        "name": "Crow's Canyon",
        "price": 100,
        "hyp": 175,
        "housePrice": 150,
        "rent": [10, 20, 35, 50, 60, 70, 90, 175, 500, 1100, 1300, 1500],
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description":
            "Crow's Ville is a rural town next to a canyon. It does have potential given enough funding.",
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "parking",
        "color": null,
        "idPrefix": "PARK",
        "name": null,
        "price": null,
        "hyp": null,
        "housePrice": null,
        "rent": null,
        "level": 0,
        "idIndex": 1,
        "mortaged": false,
        "description": null,
        "transportationPrice": 200,
        "backgroundColor": null,
      },
      {
        "type": "land",
        "color": Colors.red.value,
        "idPrefix": "DB",
        "name": "Crow's Ville",
        "price": 100,
        "hyp": 200,
        "housePrice": 150,
        "rent": [50, 10, 20, 35, 50, 60, 70, 90, 200, 600, 1400, 1700, 2000],
        "level": 0,
        "idIndex": 2,
        "mortaged": false,
        "description":
            "Crow's Ville is a rural town next to a canyon. It does have potential given enough funding.",
        "transportationPrice": 200,
        "backgroundColor": null,
      }
    ],
    "settings": {
      "name": "Game 1",
      "remotelyBuild": true,
      "goBonus": 200,
      "maxTurnes": 99999,
      "mustAuction": false,
      "startingMoney": 1500,
      "hackerScreen": false,
      "interest": 5,
      "dtlPrice": 2000,
      "startProperties": 0,
      "transportPassGo": false,
      "allowDiceSelect": false,
      "allowPriceChanges": false,
      "generateNames": false,
      "receiveProperties": true
    },
    "extensions": ["transportation"],
    "ui": {"screenState": "idle", "showDealScreen": false, "shouldMove": true},
    "rentPayed": false,
    "findingsIndex": 1,
    "eventIndex": 5,
    "mapConfiguration": "classic",
    "dealData": {
      "payAmount": 0,
      "receivableProperties": [],
      "receiveProperties": [],
      "payableProperties": [],
      "payProperties": [],
      "price": 0,
      "valid": [true, true],
      "playerChecked": false,
      "dealerChecked": false,
      "dealer": null,
    },
    "bankData": null,
    "version": "0.4.2",
    "lostPlayers": [],
    "bot": false,
    "transported": false
  }
};
